# DeathTpPlus 3.4.1597 by Don Redhorse and mung3r
#
# Configuration File for DeathTpPlus.
#
# For detailed assistance please visit: http://dev.bukkit.org/server-mods/deathtpplus/

#------- Default Configuration

# Configuration Version
configVer: "3.3"

# Config Log Enabled
ConfigLogEnabled: true

# Debug Log Enabled
# Enable more logging.. could be messy!
DebugLogEnabled: false

# Log to File
LogToFile: true

# Log to Console
LogToConsole: true

# Check for Update
# Will check if there is a new version of the plugin out.
checkForUpdate: true

# Auto Update Config
# This will overwrite any changes outside the configuration parameters!
autoUpdateConfig: false

# Save Config
# This will overwrite any changes outside the configuration parameters!
# Only needed if you use ingame commands to change the configuration.
saveConfig: false

#-------- Plugin Configuration


# Date Format (For formatting, see http://download.oracle.com/javase/6/docs/api/java/text/SimpleDateFormat.html) 
dateFormat: 'MM/dd/yyyy'

# Time Format (For formatting, see http://download.oracle.com/javase/6/docs/api/java/text/SimpleDateFormat.html) 
timeFormat: 'hh:mm a'

# Enable Lockette Support
enableLockette: true

# Enable LWC Support
enableLWC: false

# Set LWC Protection to public instead of removing it
lwcPublic: false

# Allow World Travel: yes, no, permissions
allowWorldTravel: 'no'

# Syntax for signs (DeathSigns and Signs on top of the DeathChest)
# Each line may be one of any custom text OR:
# {name} for player name
# {date} for day of death
# {time} for time of death (server time)
# {reason} for cause of death
# REMEMBER: LINES ARE LIMITED TO 15 CHARACTERS, AND DON'T FORGET THE QUOTES!
signSyntax:
   Line1: "{name}"
   Line2: "RIP"
   Line3: "{date}"
   Line4: "{time}"

# Should we try to only use air to create signs and chests.
# WARNING: This can mean that NO DeathSigns or DeathChest are created.
#          Use at your own risk!
tryToUseOnlyAir: false


# Teleport to highest point of the map or use the save location feature
# This means ground level or NO teleport into the nether!
# Note: Save location feature will display the location of the death if it doesn't find a save spot
# and not teleport the player in this case.
teleportToHighestPoint: false

# Enable Features

# Enable DeathTp Features
enableDeathtp: true

# Show the death messages on the server
enableDeathNotify: true

# Show kill, death streaks and multi kill messages
enableStreaks: true

# Enable DeathSigns
enableDeathSigns: true


# Enable DeathChest Feature
enableDeathChest: true


# Enable the Tomb feature
enableTomb: true

# Log the deaths to file
enableDeathLog: true

# Item ID of the item you must have in your hand to teleport. Will remove 1 of these when the command is given. Leave 0 for free teleports 
chargeItem: "0"

# Economy costs for teleport to place of death, leave 0 if you don't want to charge
deathtpCost: "10"

#--------- DeathTp Features


# Allow players to access the deathtp command (Override permissions)
allowDeathtpForAll: false


#--------- DeathMessages Features

# Disable the death messages on specific worlds
disableDeathMessagesInSpecifiedWorlds: false

# Worlds on which death messages are disabled
disabledDeathMessagesWorlds:
    - "none"

    
# Window of time (in milliseconds) to count kills towards a multikill
multiKillTimeWindow: "5000"


# Use DisplayName for Broadcast Messages
# Note: Depending on the characters you are using in the names this can cause NPE's!
useDisplayNameforBroadcasts: false

#--------- DeathChest Features (General)



# Place a Sign on the DeathChest
showDeathChestSign: true

#  Prevent non-Op players from destroying DeathChests if true (destroyQuickLoot overrides)
allowDeathChestDestroy: false

# Show status messages to the player
showDeathChestStatusMessage: true

# Save DeathChest Listing between server reloads
saveDeathChestList: true

# Stop DeathChest creation next to existing chests if true (IF set to true it could allow users to circumvent chest protection.)
allowInterfere: false

# We normally check to make sure we aren't trying to create a chest in the void.
# If you handle or modify the void with another plugin, you can disable that check here.
# This option should be true for most servers.
voidCheck: true

# If you are not locking your chests with Lockette or LWC but still want them to be
# protected against Creeper explosions, or you want your chests to be protected even
# after they are unlocked, enable this
creeperProtection: false

# Keep dropped experience when quicklooting
keepExperienceOnQuickLoot: false

#--------- DeathChest features (Removal

# Destroy DeathChest on player quickloot
destroyOnQuickLoot: true

# Remove DeathChest after RemoveTime
removeDeathChest: true

# Remove the DeathChest after x Seconds if removeDeathChest is true
removeDeathChestTime: "3600"

# Immediately remove DeathChest once it is empty, overriding all other timeout options
# WARNING: THIS IS A PROCESSOR-INTENSIVE OPTION
removeDeathChestWhenEmpty: false

# Never remove a DeathChest unless it is empty
# WARNING: THIS IS A PROCESSOR-INTENSIVE OPTION
keepDeathChestUntilEmpty: false

#--------- DeathChest Features (Security

# Remove security after timeout
removeDeathChestSecurity: false

# Timeout for Security Removal in seconds
removeDeathChestSecurityTimeOut: "3600"

#--------- Tomb Features



# Price for createing a Tomb
tombCost: "10"

# Amount of Tombs a player can have
maxTomb: 1

# Use the Tomb as a respawn point
useTombAsRespawnPoint: false

# Keyword used to detect a Tomb
tombKeyWord: "[Tomb]"

# Number of death before destruction of every tomb of the player
# without resetting the counter. If set to 2, every 2 deaths, the tombs are destroyed. (Sign is dropped) 0: = Disabled
maxDeaths: 0

# When a Tomb is destroyed, the respawn point is reset.
resetTombRespawn: false


